repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        entry: black
        args: [--config=pyproject.toml, --diff]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
        entry: ruff
        args: [--config=pyproject.toml]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.5
    hooks:
      # Compile requirements
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
